server:
  port: ${PORT:8866}
message: Configuracion de la categoria en el servidor levantado
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://localhost:3306/crudcloud?serverTimezone=UTC
    username: root
  jpa:
    show-sql: true  
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
cloud:
  config:
    url: http://localhost:8860
eureka:
  client:
    register-with-eureka: true
    # fetch-registry: false
    serviceurl:
      defaultZone: http://localhost:8850/eureka/
