server:
  port: ${PORT:8850}

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

# message: Servicio de registro y descubrimiento levantado en el servidor!
